language: bash

sudo: required

services: docker

env:
  global:
    - VERSION: "0.10.0"
    - BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
    - REPO: $DOCKER_USERNAME
    - TAG_MINOR: ${VERSION%.*}
    - TAG_MAJOR: ${VERSION%%.*}
    - GIT_REPO_LINK: "https://github.com/OlegGorj/openvpn-on-docker.git#master"
    - IMAGE: "openvpn"
    - TAG: "latest"

branches:
  only:
    - dev_branch
    - /^(?i:deploy)-.*$/

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

before_script:
    - image="oleggorj/openvpn"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker push "$image"
    - docker run --rm "$image" openvpn --version || true
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images
